[theme]
base = "light"
primaryColor = "#176A63"
backgroundColor = "#FAF9F6"
secondaryBackgroundColor = "#EEEDE7"
textColor = "#182B30"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
headless = true
